[package]
name = "xshell-macros"
description = "Private implementation detail of xshell crate"
version = "0.1.12"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true
